apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keptn-service.serviceAccountName" . }}
  labels:
    {{- include "keptn-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
# Role for accessing secrets in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-generic-job-service
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
      - "persistentvolumeclaims"
      - "jobs"
    verbs:
      - "*"
  - apiGroups:
      - "batch"
      - "extensions"
    resources:
      - "jobs"
    verbs:
      - "*"
---
# Bind role for accessing secrets onto the generic-job-service service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-generic-job-service
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-generic-job-service
subjects:
  - kind: ServiceAccount
    name: {{ include "keptn-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
