---
# Deployment of our keptn-generic-job-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptn-generic-job-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: keptn-generic-job-service
  replicas: 1
  template:
    metadata:
      labels:
        run: keptn-generic-job-service
    spec:
      containers:
        - name: keptn-generic-job-service
          image: didiladi/keptn-generic-job-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: INIT_CONTAINER_CONFIGURATION_SERVICE_API_ENDPOINT
              value: "http://configuration-service:8080"
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: JOB_NAMESPACE
              value: 'keptn'
        - name: distributor
          image: keptn/distributor:0.8.0-alpha
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
      serviceAccountName: keptn-generic-job-service
---
# Expose keptn-generic-job-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: keptn-generic-job-service
  namespace: keptn
  labels:
    run: keptn-generic-job-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: keptn-generic-job-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-generic-job-service
  namespace: keptn
---
# Role for accessing secrets in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-generic-job-service
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
      - "persistentvolumeclaims"
      - "jobs"
    verbs:
      - "*"
  - apiGroups:
      - "batch"
      - "extensions"
    resources:
      - "jobs"
    verbs:
      - "*"
---
# Bind role for accessing secrets onto the generic-job-service service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-generic-job-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-generic-job-service
subjects:
  - kind: ServiceAccount
    name: keptn-generic-job-service
    namespace: keptn

